CREATE TABLE EV.EV005 (
    EV005_IT_ID      SERIAL PRIMARY KEY NOT NULL,
    EV005_IT_IDINST  INTEGER NOT NULL,
    EV005_VC_METOD   VARCHAR NOT NULL,
    EV005_VC_DESC    VARCHAR NOT NULL,
    EV005_VC_DESCAUX VARCHAR,
    EV005_IT_SITUAC  NUMERIC(3,0) NOT NULL,
    EV005_DT_ULTATU  TIMESTAMP NOT NULL,
    EV005_DT_INCLUS  TIMESTAMP NOT NULL
)

ALTER TABLE EV.EV005 ADD FOREIGN KEY (EV005_IT_IDINST) REFERENCES AD.AD001(AD001_IT_ID);